### ISSUE TITLE
Support cancellation

### ISSUE THREAD

**Issue by abatishchev** [thomaslevesque/AspNetCore.AsyncInitialization#11]
Please add `CancellationToken` to `InitializeAsync`. This would be a breaking change and thus require to bump the version to 2.0.

Or you can add an overload. To simplify the consumption, try to use new C# feature of default interface Implementation, i.e. the overload without CT pass CT.None to the overload with it. Or you can provide simple abstract class that would do it for me. So I'll have less boilerplate code to write.

Makes sense?

**Comment by thomaslevesque** [comment]
Hi @abatishchev,

Thanks for the suggestion.

To be honest, I thought about this, but couldn't think of a case where it would make sense. As far as I know, there's no way to interrupt the startup of an ASP.NET Core app. Where would the cancellation token come from?

Do you have a specific scenario in mind?

> To simplify the consumption, try to use new C# feature of default interface Implementation

I don't think I'd do that. C# 8 and .NET Core 3.0 aren't RTM yet, and pre-.NET Core 3.0 runtimes won't support DIM. Also, .NET Framework will never support it. I'd rather not write a library that only works on .NET Core 3.0 :wink:

**Comment by abatishchev** [comment]
You're right, no one (i.e. ASP.NET Core infrastructure) would pass cancellation token. I misused your library so have a way to pass but this is wrong and make no sense. Don't work very late hours :)

If DIM requires .NET Core and won't work on .NET Framework than it sucks. Imo it sucks anyway but this makes it even worse.

**Comment by thomaslevesque** [comment]
> If DIM requires .NET Core and won't work on .NET Framework than it sucks. Imo it sucks anyway but this makes it even worse.

I like the feature, but the fact that it won't work on all runtimes makes it impossible to use in a portable way...
