### ISSUE TITLE
In which case we will benefit from this?

### ISSUE THREAD

**Issue by brunopbarrote** [thomaslevesque/AspNetCore.AsyncInitialization#12]
Hello!

I've a simple question, in which scenario would we benefit from using this?
I think would be good, if add some samples, or at least mention some scenarios, it would make this more attractive.

Kind regards!

**Comment by thomaslevesque** [comment]
Hi @brunopbarrote,

Thanks for your interest. Yeah, I guess I could be more explicit about what this library is for. The idea is to perform initialization tasks (such as seeding a database, creating a service bus queue, etc) that should run asynchronously before the application actually starts. You can find more information in my [blog post](https://www.thomaslevesque.com/2018/09/25/asynchronous-initialization-in-asp-net-core-revisited/).
