### ISSUE TITLE
Why do you support transient services?

### ISSUE THREAD

**Issue by david-peden-q2** [thomaslevesque/AspNetCore.AsyncInitialization#13]
Shouldn't all registered initializers be singletons? Logically, I don't know that the registration type will actually make a difference since any given initializer should only ever be instantiated once and run once but semantically, I think it makes a difference.

And if not, I think your API surface should explicitly call out the type of underlying registration.

**Comment by thomaslevesque** [comment]
Hi @david-peden-q2,

At first glance, it seems it would make more sense to register initializers as singletons. But as you say, it doesn't really make a difference, and the fact isn't surfaced in the API anyway. But there's actually a more important reason: singletons can't depend on scoped services, whereas transient services can. The [`InitAsync` method](https://github.com/thomaslevesque/AspNetCore.AsyncInitialization/blob/90d2bae57c1708ee65e47228665fe49d07b3cd73/src/AspNetCore.AsyncInitialization/Hosting/AsyncInitializationWebHostExtensions.cs#L18) specifically creates a scope to support this.

**Comment by davidpeden3** [comment]
That's a fair point but why would you ever have a scoped service injected? What scope could there be? It seems that any service that would be necessary to initialize an application would be fairly one-off in nature and not have a dependency on some sort of scope. Maybe I'm missing the point?

**Comment by thomaslevesque** [comment]
> That's a fair point but why would you ever have a scoped service injected? What scope could there be?

The most common example I can think of is an EF Core `DbContext`. By default, it's registered as Scoped, as it should be. And it's typically something that you might need in an initializer. If initializers were registered as Singleton, it wouldn't be possible to inject a `DbContext` into them (unless you change the lifetime of the `DbContext` to Singleton or Transient, but it's probably not a good idea since it would affect the whole app...)

**Comment by davidpeden3** [comment]
My use case that led me down the path of discovering this repo was initializing hosts needing data from other APIs (via `HttpClient`). I had not considered EF specifically.

Thanks for providing a concrete example.

**Comment by thomaslevesque** [comment]
You're welcome! Thanks for your interest.
